#!/bin/bash
#set -x

#I assume 
#   the wrapper command format is  "arm-command", 
#   the origin toolchain name is "arm-what-ever-you-want-gcc
#   the gcc must exist 

toolname=`echo ${0##/*/} | cut -d '-' -f 2`;
tooltype=`ls $ARM_TOOLPATH/bin/arm-*-gcc`

if [ -z $ARM_TOOLPATH ]; then
	echo '$ARM_TOOLPATH' is not set;
	exit 1;
fi

if [ ! -e $tooltype ]; then
	echo "Can't find tooltype";
	exit 1;
fi

tooltype=${tooltype##*arm-}
tooltype=${tooltype%%-gcc}

realtool="$ARM_TOOLPATH/bin/arm-$tooltype-$toolname";

if [ -z $toolname ]; then
	echo "Unknown ARM tool";
	exit 1;
fi

if [ ! -x $realtool ]; then
	"file is not executable"
	exit 1;
fi

$realtool $*
